# Generated by Django 2.2.5 on 2020-04-25 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='factory_manager.Workshop'),
        ),
        migrations.AlterField(
            model_name='cnc',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='factory_manager.Area'),
        ),
        migrations.AlterField(
            model_name='cnc',
            name='workshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='factory_manager.Workshop'),
        ),
    ]
