# Generated by Django 2.2.5 on 2020-04-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_manager', '0004_auto_20200422_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnc',
            name='congestion',
            field=models.IntegerField(default=0),
        ),
    ]
