# Generated by Django 2.2.5 on 2020-04-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_manager', '0005_cnc_congestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnc',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
