# Generated by Django 2.2.5 on 2020-04-24 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_manager', '0006_cnc_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnc',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 18, 56, 41, 337150)),
        ),
    ]
