# Generated by Django 2.2.5 on 2020-04-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_manager', '0007_auto_20200424_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnc',
            name='date',
            field=models.IntegerField(default=0),
        ),
    ]
