# Generated by Django 2.2.5 on 2020-04-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='phone',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
