# Generated by Django 2.2.5 on 2020-04-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0002_auto_20200416_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='FIO',
            field=models.CharField(default='faf', max_length=120),
        ),
    ]
