# Generated by Django 2.2.5 on 2020-04-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0003_stuff_fio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuff',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stuff',
            name='second_name',
        ),
        migrations.RemoveField(
            model_name='stuff',
            name='surname',
        ),
        migrations.AlterField(
            model_name='stuff',
            name='FIO',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
