# Generated by Django 2.2.5 on 2020-04-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='position',
            new_name='access_code',
        ),
    ]
