# Generated by Django 2.2.5 on 2020-04-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200416_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='access_code',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
