# Generated by Django 2.2.5 on 2020-04-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200420_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(blank=True, choices=[('Начальник цеха', 'Начальник цеха'), ('Начальник участка', 'Начальник участка'), ('Начальник ремонтной службы', 'Начальник ремонтной службы'), ('Работник', 'Работник')], max_length=30, null=True),
        ),
    ]
