# Generated by Django 2.2.5 on 2020-04-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_for_boss_repair',
            name='type_request',
            field=models.CharField(blank=True, choices=[('Выполнено', 'Выполнено'), ('Выполняется', 'Выполняется'), ('Выполнить невозможно', 'Выполнить невозможно'), ('Отправлено', 'Отправлено')], default='Профилактика', max_length=120, null=True),
        ),
    ]
