# Generated by Django 2.2.5 on 2020-04-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0002_auto_20200422_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request_for_boss_repair',
            old_name='date',
            new_name='date_deadline',
        ),
        migrations.AddField(
            model_name='request_for_boss_repair',
            name='date_request',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
